import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import HeaderAction from '../components/layouts/HeaderAction';
import FooterLinks from '../components/layouts/FooterLink';
import '../styles/global.css'
import '../styles/syntax-coloring.css'
import styles from '../styles/shared.module.css'

const inter = Inter({ subsets: ['latin'] })

const tabs = [
  {
    link: '/',
    label: 'HOME',
  },
  {
    link: 'portfolio',
    label: 'MyPage',
  },
  {
    link: 'blog',
    label: 'TechBlog',
  },
];


export const metadata: Metadata = {
  title: 'NotionBlog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <div className={styles.container}>
            <HeaderAction {...{ tabs }} />
              <div className={styles.content}>
                {children}
              </div>
            <FooterLinks /> 
        </div>
      </body>
    </html>
  )
}
